### ISSUE TITLE
Binary tag releases

### ISSUE THREAD

**Issue by xintron** [rdebath/PuTTY#3]
Would it be possible to publish the binaries within the tag releases on GitHub?

**Comment by rdebath** [comment]
Not sure what you're asking for here.
My changes are a set of patches so the only 'release' is the default branch, the individual change descriptions are in the commit messages as each commit mostly corresponds to a single patch.

I'm copying the tags for all of Simon's releases as they're occasionally useful, so that's okay, and Simon has a change log at https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

As for binaries, I automatically recreate the [binary branch](https://github.com/rdebath/PuTTY/tree/binary) each time I push an update (or rebase) where you can download my modified PuTTY from if you wish. But generally I suggest you compile your own or get someone you know to do it for you.

Simon's binaries are all [on his website](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) and I will not be copying them here.

**Comment by xintron** [comment]
I missed the part in the readme explaining that master is without the patches applied. What your saying makes sense and I now understand that the tags are actually the original putty tags, without the patches applied.
